en:
  languageCode: en
  languageName: English
  title: Hugolify demo
  weight: 1
  contentDir: content/en

ja:
  languageCode: ja
  languageName: 日本語
  title: Hugolify デモ
  weight: 2
  contentDir: content/ja
